// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types'
import type * as prismicClient from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutPageDocumentDataSlicesSlice =
  | AboutTitleBlockSlice
  | RectTextBlockSlice
  | FormationSlice
  | RoundTextBlockSlice
  | AboutContactSlice

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutPageDocumentData>,
    'about_page',
    Lang
  >

type ComportementalistePageDocumentDataSlicesSlice =
  | ServiceInfoBlockSlice
  | HorizontalSliderBlocksSlice

/**
 * Content for ComportementalistePage documents
 */
interface ComportementalistePageDocumentData {
  /**
   * Slice Zone field in *ComportementalistePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: comportementaliste_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ComportementalistePageDocumentDataSlicesSlice>
}

/**
 * ComportementalistePage document from Prismic
 *
 * - **API ID**: `comportementaliste_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComportementalistePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ComportementalistePageDocumentData>,
    'comportementaliste_page',
    Lang
  >

type HomePageDocumentDataSlicesSlice =
  | ServicesBlockSlice
  | ReviewsBlockSlice
  | ProblematicsBlockSlice
  | SocialMediaBlockSlice

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * module hero banner field in *Home Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.module_hero_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_hero_banner: prismic.ContentRelationshipField<'module_hero_banner'>

  /**
   * module contact banner field in *Home Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.module_contact_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_contact_banner: prismic.ContentRelationshipField<'module_contact_banner'>

  /**
   * site footer field in *Home Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.site_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  site_footer: prismic.ContentRelationshipField<'site_footer'>

  /**
   * catus field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.catus
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  catus: prismic.RichTextField

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    'home_page',
    Lang
  >

type InfoPageDocumentDataSlicesSlice = ServiceInfoBlockSlice

/**
 * Content for Info Page documents
 */
interface InfoPageDocumentData {
  /**
   * Module Banner field in *Info Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: info_page.module_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_banner: prismic.ContentRelationshipField<'module_photo_banner'>

  /**
   * site footer field in *Info Page*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: info_page.site_footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  site_footer: prismic.LinkToMediaField

  /**
   * Slice Zone field in *Info Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: info_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InfoPageDocumentDataSlicesSlice>
}

/**
 * Info Page document from Prismic
 *
 * - **API ID**: `info_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InfoPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<InfoPageDocumentData>,
    'info_page',
    Lang
  >

type ModuleContactBannerDocumentDataSlicesSlice = never

/**
 * Content for Module Contact Banner documents
 */
interface ModuleContactBannerDocumentData {
  /**
   * Title field in *Module Contact Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Title Alternative field in *Module Contact Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.title_alternative
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_alternative: prismic.RichTextField

  /**
   * Alternative Title field in *Module Contact Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.alternative_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  alternative_title: prismic.RichTextField

  /**
   * Email Label field in *Module Contact Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.email_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_label: prismic.KeyTextField

  /**
   * email field in *Module Contact Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField

  /**
   * Tel Label field in *Module Contact Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.tel_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tel_label: prismic.KeyTextField

  /**
   * Tel field in *Module Contact Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.tel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tel: prismic.KeyTextField

  /**
   * Contact Note field in *Module Contact Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.contact_note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_note: prismic.RichTextField

  /**
   * Contact Planning CTA Label field in *Module Contact Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.contact_planning_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_planning_cta_label: prismic.KeyTextField

  /**
   * Illustration Head field in *Module Contact Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.illustration_head
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_head: prismic.ImageField<never>

  /**
   * Illustration Foot field in *Module Contact Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.illustration_foot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_foot: prismic.ImageField<never>

  /**
   * Illustration Social Cats field in *Module Contact Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.illustration_social_cats
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_social_cats: prismic.ImageField<never>

  /**
   * Slice Zone field in *Module Contact Banner*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: module_contact_banner.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ModuleContactBannerDocumentDataSlicesSlice>
}

/**
 * Module Contact Banner document from Prismic
 *
 * - **API ID**: `module_contact_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleContactBannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModuleContactBannerDocumentData>,
    'module_contact_banner',
    Lang
  >

/**
 * Content for Module Hero Banner documents
 */
interface ModuleHeroBannerDocumentData {
  /**
   * illustration field in *Module Hero Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.illustration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>

  /**
   * illustration alt field in *Module Hero Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.illustration_alt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  illustration_alt: prismic.KeyTextField

  /**
   * illustration logo field in *Module Hero Banner*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.illustration_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  illustration_logo: prismic.ContentRelationshipField<'module_logo'>

  /**
   * logo text field in *Module Hero Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.logo_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  logo_text: prismic.RichTextField

  /**
   * text field in *Module Hero Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * module logo field in *Module Hero Banner*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.module_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_logo: prismic.ContentRelationshipField<'module_logo'>

  /**
   * bubble chat field in *Module Hero Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_hero_banner.bubble_chat
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bubble_chat: prismic.ImageField<never>
}

/**
 * Module Hero Banner document from Prismic
 *
 * - **API ID**: `module_hero_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleHeroBannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModuleHeroBannerDocumentData>,
    'module_hero_banner',
    Lang
  >

/**
 * Content for Module Logo documents
 */
interface ModuleLogoDocumentData {
  /**
   * image field in *Module Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_logo.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * link field in *Module Logo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: module_logo.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * size field in *Module Logo*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: module_logo.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  size: prismic.NumberField

  /**
   * no link field in *Module Logo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: module_logo.no_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  no_link: prismic.BooleanField
}

/**
 * Module Logo document from Prismic
 *
 * - **API ID**: `module_logo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleLogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModuleLogoDocumentData>,
    'module_logo',
    Lang
  >

/**
 * Content for Module Photo Banner documents
 */
interface ModulePhotoBannerDocumentData {
  /**
   * image field in *Module Photo Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * title field in *Module Photo Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * description field in *Module Photo Banner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Bubble Desktop field in *Module Photo Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.bubble_desktop
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bubble_desktop: prismic.ImageField<never>

  /**
   * Bubble Mobile field in *Module Photo Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.bubble_mobile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bubble_mobile: prismic.ImageField<never>

  /**
   * Bubble Image field in *Module Photo Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_photo_banner.bubble_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bubble_image: prismic.ImageField<never>
}

/**
 * Module Photo Banner document from Prismic
 *
 * - **API ID**: `module_photo_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModulePhotoBannerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModulePhotoBannerDocumentData>,
    'module_photo_banner',
    Lang
  >

/**
 * Content for Module Service documents
 */
interface ModuleServiceDocumentData {
  /**
   * Title field in *Module Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_service.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Module Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_service.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Image field in *Module Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_service.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Image Position field in *Module Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_service.image_position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_position: prismic.KeyTextField
}

/**
 * Module Service document from Prismic
 *
 * - **API ID**: `module_service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModuleServiceDocumentData>,
    'module_service',
    Lang
  >

/**
 * Content for Module Social Media documents
 */
interface ModuleSocialMediaDocumentData {
  /**
   * Title field in *Module Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: module_social_media.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Link field in *Module Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: module_social_media.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * Icon field in *Module Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: module_social_media.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>
}

/**
 * Module Social Media document from Prismic
 *
 * - **API ID**: `module_social_media`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleSocialMediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ModuleSocialMediaDocumentData>,
    'module_social_media',
    Lang
  >

/**
 * Item in *Partners Page → partners*
 */
export interface PartnerspageDocumentDataPartnersItem {
  /**
   * name field in *Partners Page → partners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.partners[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * link field in *Partners Page → partners*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.partners[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * fullWidth field in *Partners Page → partners*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: partnerspage.partners[].fullwidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fullwidth: prismic.BooleanField

  /**
   * logo field in *Partners Page → partners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.partners[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>
}

/**
 * Content for Partners Page documents
 */
interface PartnerspageDocumentData {
  /**
   * page title field in *Partners Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField

  /**
   * banner field in *Partners Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>

  /**
   * description field in *Partners Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * partners field in *Partners Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerspage.partners[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  partners: prismic.GroupField<Simplify<PartnerspageDocumentDataPartnersItem>>
}

/**
 * Partners Page document from Prismic
 *
 * - **API ID**: `partnerspage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnerspageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PartnerspageDocumentData>,
    'partnerspage',
    Lang
  >

/**
 * Content for Site Footer documents
 */
interface SiteFooterDocumentData {
  /**
   * Credits CTA Label field in *Site Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.credits_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credits_cta_label: prismic.KeyTextField

  /**
   * Credits Content field in *Site Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.credits_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  credits_content: prismic.RichTextField

  /**
   * Legal Mention CTA Label field in *Site Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.legal_mention_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  legal_mention_cta_label: prismic.KeyTextField

  /**
   * Legal Mention Content field in *Site Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.legal_mention_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  legal_mention_content: prismic.RichTextField

  /**
   * Module Logo field in *Site Footer*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.module_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_logo: prismic.ContentRelationshipField<'module_logo'>

  /**
   * Copyright Content field in *Site Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.copyright_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright_content: prismic.RichTextField

  /**
   * Planning Iframe field in *Site Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_footer.planning_iframe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  planning_iframe: prismic.KeyTextField
}

/**
 * Site Footer document from Prismic
 *
 * - **API ID**: `site_footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteFooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteFooterDocumentData>,
    'site_footer',
    Lang
  >

type SiteHeaderDocumentDataSlicesSlice = AnnouncementBarSlice | HeaderLinkSlice

/**
 * Content for Site Header documents
 */
interface SiteHeaderDocumentData {
  /**
   * logo field in *Site Header*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: site_header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo: prismic.ContentRelationshipField<'module_logo'>

  /**
   * Slice Zone field in *Site Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: site_header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SiteHeaderDocumentDataSlicesSlice>
}

/**
 * Site Header document from Prismic
 *
 * - **API ID**: `site_header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteHeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteHeaderDocumentData>,
    'site_header',
    Lang
  >

export type AllDocumentTypes =
  | AboutPageDocument
  | ComportementalistePageDocument
  | HomePageDocument
  | InfoPageDocument
  | ModuleContactBannerDocument
  | ModuleHeroBannerDocument
  | ModuleLogoDocument
  | ModulePhotoBannerDocument
  | ModuleServiceDocument
  | ModuleSocialMediaDocument
  | PartnerspageDocument
  | SiteFooterDocument
  | SiteHeaderDocument

/**
 * Primary content in *AboutContact → Primary*
 */
export interface AboutContactSliceDefaultPrimary {
  /**
   * cta text field in *AboutContact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField

  /**
   * cta image field in *AboutContact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.primary.cta_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_image: prismic.ImageField<never>

  /**
   * cta link field in *AboutContact → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField
}

/**
 * Primary content in *AboutContact → Items*
 */
export interface AboutContactSliceDefaultItem {
  /**
   * link field in *AboutContact → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * text field in *AboutContact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.items[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField

  /**
   * icon field in *AboutContact → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_contact.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>
}

/**
 * Default variation for AboutContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: AboutContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutContactSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutContactSliceDefaultPrimary>,
  Simplify<AboutContactSliceDefaultItem>
>

/**
 * Slice variation for *AboutContact*
 */
type AboutContactSliceVariation = AboutContactSliceDefault

/**
 * AboutContact Shared Slice
 *
 * - **API ID**: `about_contact`
 * - **Description**: AboutContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutContactSlice = prismic.SharedSlice<
  'about_contact',
  AboutContactSliceVariation
>

/**
 * Primary content in *AboutTitleBlock → Primary*
 */
export interface AboutTitleBlockSliceDefaultPrimary {
  /**
   * text field in *AboutTitleBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_title_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * addition class text field in *AboutTitleBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_title_block.primary.addition_class_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  addition_class_text: prismic.KeyTextField

  /**
   * image field in *AboutTitleBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_title_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * additional class image field in *AboutTitleBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_title_block.primary.additional_class_image
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  additional_class_image: prismic.KeyTextField
}

/**
 * Default variation for AboutTitleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: AboutTitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTitleBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutTitleBlockSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *AboutTitleBlock*
 */
type AboutTitleBlockSliceVariation = AboutTitleBlockSliceDefault

/**
 * AboutTitleBlock Shared Slice
 *
 * - **API ID**: `about_title_block`
 * - **Description**: AboutTitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTitleBlockSlice = prismic.SharedSlice<
  'about_title_block',
  AboutTitleBlockSliceVariation
>

/**
 * Primary content in *AnnouncementBar → Primary*
 */
export interface AnnouncementBarSliceDefaultPrimary {
  /**
   * text field in *AnnouncementBar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: announcement_bar.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for AnnouncementBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBarSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AnnouncementBarSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *AnnouncementBar*
 */
type AnnouncementBarSliceVariation = AnnouncementBarSliceDefault

/**
 * AnnouncementBar Shared Slice
 *
 * - **API ID**: `announcement_bar`
 * - **Description**: AnnouncementBar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnouncementBarSlice = prismic.SharedSlice<
  'announcement_bar',
  AnnouncementBarSliceVariation
>

/**
 * Primary content in *Formation → Primary*
 */
export interface FormationSliceDefaultPrimary {
  /**
   * cta text field in *Formation → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField

  /**
   * cta bg image field in *Formation → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.primary.cta_bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_bg_image: prismic.ImageField<never>
}

/**
 * Primary content in *Formation → Items*
 */
export interface FormationSliceDefaultItem {
  /**
   * year field in *Formation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.items[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField

  /**
   * name field in *Formation → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField

  /**
   * certificate field in *Formation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.items[].certificate
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  certificate: prismic.KeyTextField

  /**
   * description field in *Formation → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formation.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

/**
 * Default variation for Formation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Formation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormationSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FormationSliceDefaultPrimary>,
  Simplify<FormationSliceDefaultItem>
>

/**
 * Slice variation for *Formation*
 */
type FormationSliceVariation = FormationSliceDefault

/**
 * Formation Shared Slice
 *
 * - **API ID**: `formation`
 * - **Description**: Formation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormationSlice = prismic.SharedSlice<
  'formation',
  FormationSliceVariation
>

/**
 * Primary content in *HeaderLinks → Items*
 */
export interface HeaderLinkSliceDefaultItem {
  /**
   * Title field in *HeaderLinks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_link.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * link field in *HeaderLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_link.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField

  /**
   * isNew field in *HeaderLinks → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: header_link.items[].isnew
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isnew: prismic.BooleanField
}

/**
 * Default variation for HeaderLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeaderLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderLinkSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<HeaderLinkSliceDefaultItem>
>

/**
 * Slice variation for *HeaderLinks*
 */
type HeaderLinkSliceVariation = HeaderLinkSliceDefault

/**
 * HeaderLinks Shared Slice
 *
 * - **API ID**: `header_link`
 * - **Description**: HeaderLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderLinkSlice = prismic.SharedSlice<
  'header_link',
  HeaderLinkSliceVariation
>

/**
 * Primary content in *HorizontalSliderBlocks → Primary*
 */
export interface HorizontalSliderBlocksSliceDefaultPrimary {
  /**
   * Illustration top field in *HorizontalSliderBlocks → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_slider_blocks.primary.illustration_top
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_top: prismic.ImageField<never>

  /**
   * top block text field in *HorizontalSliderBlocks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_slider_blocks.primary.top_block_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  top_block_text: prismic.RichTextField

  /**
   * Illustration bottom field in *HorizontalSliderBlocks → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_slider_blocks.primary.illustration_bottom
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_bottom: prismic.ImageField<never>

  /**
   * bottom block text field in *HorizontalSliderBlocks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_slider_blocks.primary.bottom_block_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bottom_block_text: prismic.RichTextField
}

/**
 * Primary content in *HorizontalSliderBlocks → Items*
 */
export interface HorizontalSliderBlocksSliceDefaultItem {
  /**
   * block text field in *HorizontalSliderBlocks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: horizontal_slider_blocks.items[].block_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  block_text: prismic.RichTextField
}

/**
 * Default variation for HorizontalSliderBlocks Slice
 *
 * - **API ID**: `default`
 * - **Description**: HorizontalSliderBlocks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalSliderBlocksSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HorizontalSliderBlocksSliceDefaultPrimary>,
  Simplify<HorizontalSliderBlocksSliceDefaultItem>
>

/**
 * Slice variation for *HorizontalSliderBlocks*
 */
type HorizontalSliderBlocksSliceVariation = HorizontalSliderBlocksSliceDefault

/**
 * HorizontalSliderBlocks Shared Slice
 *
 * - **API ID**: `horizontal_slider_blocks`
 * - **Description**: HorizontalSliderBlocks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HorizontalSliderBlocksSlice = prismic.SharedSlice<
  'horizontal_slider_blocks',
  HorizontalSliderBlocksSliceVariation
>

/**
 * Primary content in *ProblematicsBlock → Primary*
 */
export interface ProblematicsBlockSliceDefaultPrimary {
  /**
   * Text 1 field in *ProblematicsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problematics_block.primary.text_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_1: prismic.RichTextField

  /**
   * Text 2 field in *ProblematicsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problematics_block.primary.text_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_2: prismic.RichTextField

  /**
   * Illustration field in *ProblematicsBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: problematics_block.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>
}

/**
 * Primary content in *ProblematicsBlock → Items*
 */
export interface ProblematicsBlockSliceDefaultItem {
  /**
   * Question field in *ProblematicsBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problematics_block.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField
}

/**
 * Default variation for ProblematicsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: ProblematicsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProblematicsBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ProblematicsBlockSliceDefaultPrimary>,
  Simplify<ProblematicsBlockSliceDefaultItem>
>

/**
 * Slice variation for *ProblematicsBlock*
 */
type ProblematicsBlockSliceVariation = ProblematicsBlockSliceDefault

/**
 * ProblematicsBlock Shared Slice
 *
 * - **API ID**: `problematics_block`
 * - **Description**: ProblematicsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProblematicsBlockSlice = prismic.SharedSlice<
  'problematics_block',
  ProblematicsBlockSliceVariation
>

/**
 * Primary content in *RectTextBlock → Primary*
 */
export interface RectTextBlockSliceDefaultPrimary {
  /**
   * text field in *RectTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rect_text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * with border field in *RectTextBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rect_text_block.primary.with_border
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  with_border: prismic.BooleanField

  /**
   * big text field in *RectTextBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rect_text_block.primary.big_text
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  big_text: prismic.BooleanField

  /**
   * text class field in *RectTextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rect_text_block.primary.text_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_class: prismic.KeyTextField
}

/**
 * Primary content in *RectTextBlock → Items*
 */
export interface RectTextBlockSliceDefaultItem {
  /**
   * image field in *RectTextBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rect_text_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * image with border field in *RectTextBlock → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: rect_text_block.items[].image_with_border
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  image_with_border: prismic.BooleanField

  /**
   * image position field in *RectTextBlock → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: rect_text_block.items[].image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<'up' | 'down'>

  /**
   * image class field in *RectTextBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rect_text_block.items[].image_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_class: prismic.KeyTextField
}

/**
 * Default variation for RectTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: RectTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RectTextBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RectTextBlockSliceDefaultPrimary>,
  Simplify<RectTextBlockSliceDefaultItem>
>

/**
 * Slice variation for *RectTextBlock*
 */
type RectTextBlockSliceVariation = RectTextBlockSliceDefault

/**
 * RectTextBlock Shared Slice
 *
 * - **API ID**: `rect_text_block`
 * - **Description**: RectTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RectTextBlockSlice = prismic.SharedSlice<
  'rect_text_block',
  RectTextBlockSliceVariation
>

/**
 * Primary content in *ReviewsBlock → Primary*
 */
export interface ReviewsBlockSliceDefaultPrimary {
  /**
   * Title field in *ReviewsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: reviews_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Detail Label field in *ReviewsBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_block.primary.detail_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  detail_label: prismic.KeyTextField

  /**
   * Link field in *ReviewsBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_block.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Primary content in *ReviewsBlock → Items*
 */
export interface ReviewsBlockSliceDefaultItem {
  /**
   * Author field in *ReviewsBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_block.items[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField

  /**
   * Review field in *ReviewsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_block.items[].review
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  review: prismic.RichTextField
}

/**
 * Default variation for ReviewsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: ReviewsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ReviewsBlockSliceDefaultPrimary>,
  Simplify<ReviewsBlockSliceDefaultItem>
>

/**
 * Slice variation for *ReviewsBlock*
 */
type ReviewsBlockSliceVariation = ReviewsBlockSliceDefault

/**
 * ReviewsBlock Shared Slice
 *
 * - **API ID**: `reviews_block`
 * - **Description**: ReviewsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReviewsBlockSlice = prismic.SharedSlice<
  'reviews_block',
  ReviewsBlockSliceVariation
>

/**
 * Primary content in *RoundTextBlock → Primary*
 */
export interface RoundTextBlockSliceDefaultPrimary {
  /**
   * text field in *RoundTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: round_text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * text class field in *RoundTextBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: round_text_block.primary.text_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_class: prismic.KeyTextField
}

/**
 * Primary content in *RoundTextBlock → Items*
 */
export interface RoundTextBlockSliceDefaultItem {
  /**
   * image field in *RoundTextBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: round_text_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * image class field in *RoundTextBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: round_text_block.items[].image_class
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_class: prismic.KeyTextField
}

/**
 * Default variation for RoundTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: RoundTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoundTextBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<RoundTextBlockSliceDefaultPrimary>,
  Simplify<RoundTextBlockSliceDefaultItem>
>

/**
 * Slice variation for *RoundTextBlock*
 */
type RoundTextBlockSliceVariation = RoundTextBlockSliceDefault

/**
 * RoundTextBlock Shared Slice
 *
 * - **API ID**: `round_text_block`
 * - **Description**: RoundTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoundTextBlockSlice = prismic.SharedSlice<
  'round_text_block',
  RoundTextBlockSliceVariation
>

/**
 * Primary content in *ServiceInfoBlock → Primary*
 */
export interface ServiceInfoBlockSliceDefaultPrimary {
  /**
   * Title field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Subtitle Up field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.subtitle_up
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle_up: prismic.RichTextField

  /**
   * Subtitle Down field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.subtitle_down
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle_down: prismic.RichTextField

  /**
   * Description field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Warning field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.warning
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  warning: prismic.RichTextField

  /**
   * Illustration field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>

  /**
   * Warning icon field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.warning_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  warning_icon: prismic.ImageField<never>

  /**
   * Has outer border field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service_info_block.primary.has_outer_border
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_outer_border: prismic.BooleanField
}

/**
 * Default variation for ServiceInfoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: ServiceInfoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceInfoBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServiceInfoBlockSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *ServiceInfoBlock → Primary*
 */
export interface ServiceInfoBlockSliceIsWhitePrimary {
  /**
   * Description field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Illustration top field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.illustration_top
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_top: prismic.ImageField<never>

  /**
   * Illustration bottom field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_info_block.primary.illustration_bottom
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration_bottom: prismic.ImageField<never>

  /**
   * Attached top to previous block\ field in *ServiceInfoBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: service_info_block.primary.attached_top
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  attached_top: prismic.BooleanField
}

/**
 * isWhite variation for ServiceInfoBlock Slice
 *
 * - **API ID**: `isWhite`
 * - **Description**: ServiceInfoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceInfoBlockSliceIsWhite = prismic.SharedSliceVariation<
  'isWhite',
  Simplify<ServiceInfoBlockSliceIsWhitePrimary>,
  never
>

/**
 * Slice variation for *ServiceInfoBlock*
 */
type ServiceInfoBlockSliceVariation =
  | ServiceInfoBlockSliceDefault
  | ServiceInfoBlockSliceIsWhite

/**
 * ServiceInfoBlock Shared Slice
 *
 * - **API ID**: `service_info_block`
 * - **Description**: ServiceInfoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceInfoBlockSlice = prismic.SharedSlice<
  'service_info_block',
  ServiceInfoBlockSliceVariation
>

/**
 * Primary content in *ServicesBlock → Primary*
 */
export interface ServicesBlockSliceDefaultPrimary {
  /**
   * Title field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: services_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField

  /**
   * Image field in *ServicesBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Primary content in *ServicesBlock → Items*
 */
export interface ServicesBlockSliceDefaultItem {
  /**
   * module service field in *ServicesBlock → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: services_block.items[].module_service
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_service: prismic.ContentRelationshipField<'module_service'>
}

/**
 * Default variation for ServicesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: ServicesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ServicesBlockSliceDefaultPrimary>,
  Simplify<ServicesBlockSliceDefaultItem>
>

/**
 * Slice variation for *ServicesBlock*
 */
type ServicesBlockSliceVariation = ServicesBlockSliceDefault

/**
 * ServicesBlock Shared Slice
 *
 * - **API ID**: `services_block`
 * - **Description**: ServicesBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesBlockSlice = prismic.SharedSlice<
  'services_block',
  ServicesBlockSliceVariation
>

/**
 * Primary content in *SocialMediaBlock → Primary*
 */
export interface SocialMediaBlockSliceDefaultPrimary {
  /**
   * Title field in *SocialMediaBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *SocialMediaBlock → Items*
 */
export interface SocialMediaBlockSliceDefaultItem {
  /**
   * Module Social Media field in *SocialMediaBlock → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_block.items[].module_social_media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  module_social_media: prismic.ContentRelationshipField<'module_social_media'>
}

/**
 * Default variation for SocialMediaBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: SocialMediaBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaBlockSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SocialMediaBlockSliceDefaultPrimary>,
  Simplify<SocialMediaBlockSliceDefaultItem>
>

/**
 * Slice variation for *SocialMediaBlock*
 */
type SocialMediaBlockSliceVariation = SocialMediaBlockSliceDefault

/**
 * SocialMediaBlock Shared Slice
 *
 * - **API ID**: `social_media_block`
 * - **Description**: SocialMediaBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaBlockSlice = prismic.SharedSlice<
  'social_media_block',
  SocialMediaBlockSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig,
    ): prismicClient.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      ComportementalistePageDocument,
      ComportementalistePageDocumentData,
      ComportementalistePageDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      InfoPageDocument,
      InfoPageDocumentData,
      InfoPageDocumentDataSlicesSlice,
      ModuleContactBannerDocument,
      ModuleContactBannerDocumentData,
      ModuleContactBannerDocumentDataSlicesSlice,
      ModuleHeroBannerDocument,
      ModuleHeroBannerDocumentData,
      ModuleLogoDocument,
      ModuleLogoDocumentData,
      ModulePhotoBannerDocument,
      ModulePhotoBannerDocumentData,
      ModuleServiceDocument,
      ModuleServiceDocumentData,
      ModuleSocialMediaDocument,
      ModuleSocialMediaDocumentData,
      PartnerspageDocument,
      PartnerspageDocumentData,
      PartnerspageDocumentDataPartnersItem,
      SiteFooterDocument,
      SiteFooterDocumentData,
      SiteHeaderDocument,
      SiteHeaderDocumentData,
      SiteHeaderDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutContactSlice,
      AboutContactSliceDefaultPrimary,
      AboutContactSliceDefaultItem,
      AboutContactSliceVariation,
      AboutContactSliceDefault,
      AboutTitleBlockSlice,
      AboutTitleBlockSliceDefaultPrimary,
      AboutTitleBlockSliceVariation,
      AboutTitleBlockSliceDefault,
      AnnouncementBarSlice,
      AnnouncementBarSliceDefaultPrimary,
      AnnouncementBarSliceVariation,
      AnnouncementBarSliceDefault,
      FormationSlice,
      FormationSliceDefaultPrimary,
      FormationSliceDefaultItem,
      FormationSliceVariation,
      FormationSliceDefault,
      HeaderLinkSlice,
      HeaderLinkSliceDefaultItem,
      HeaderLinkSliceVariation,
      HeaderLinkSliceDefault,
      HorizontalSliderBlocksSlice,
      HorizontalSliderBlocksSliceDefaultPrimary,
      HorizontalSliderBlocksSliceDefaultItem,
      HorizontalSliderBlocksSliceVariation,
      HorizontalSliderBlocksSliceDefault,
      ProblematicsBlockSlice,
      ProblematicsBlockSliceDefaultPrimary,
      ProblematicsBlockSliceDefaultItem,
      ProblematicsBlockSliceVariation,
      ProblematicsBlockSliceDefault,
      RectTextBlockSlice,
      RectTextBlockSliceDefaultPrimary,
      RectTextBlockSliceDefaultItem,
      RectTextBlockSliceVariation,
      RectTextBlockSliceDefault,
      ReviewsBlockSlice,
      ReviewsBlockSliceDefaultPrimary,
      ReviewsBlockSliceDefaultItem,
      ReviewsBlockSliceVariation,
      ReviewsBlockSliceDefault,
      RoundTextBlockSlice,
      RoundTextBlockSliceDefaultPrimary,
      RoundTextBlockSliceDefaultItem,
      RoundTextBlockSliceVariation,
      RoundTextBlockSliceDefault,
      ServiceInfoBlockSlice,
      ServiceInfoBlockSliceDefaultPrimary,
      ServiceInfoBlockSliceIsWhitePrimary,
      ServiceInfoBlockSliceVariation,
      ServiceInfoBlockSliceDefault,
      ServiceInfoBlockSliceIsWhite,
      ServicesBlockSlice,
      ServicesBlockSliceDefaultPrimary,
      ServicesBlockSliceDefaultItem,
      ServicesBlockSliceVariation,
      ServicesBlockSliceDefault,
      SocialMediaBlockSlice,
      SocialMediaBlockSliceDefaultPrimary,
      SocialMediaBlockSliceDefaultItem,
      SocialMediaBlockSliceVariation,
      SocialMediaBlockSliceDefault,
    }
  }
}
