// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * module hero banner field in *Home Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.module_hero_banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_hero_banner: prismicT.RelationField<"module_hero_banner">;
    /**
     * module contact banner field in *Home Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.module_contact_banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_contact_banner: prismicT.RelationField<"module_contact_banner">;
    /**
     * site footer field in *Home Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.site_footer
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    site_footer: prismicT.RelationField<"site_footer">;
    /**
     * Slice Zone field in *Home Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = ServicesBlockSlice | ReviewsBlockSlice | ProblematicsBlockSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
/** Content for Module Contact Banner documents */
interface ModuleContactBannerDocumentData {
    /**
     * Title field in *Module Contact Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Email Label field in *Module Contact Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.email_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email_label: prismicT.KeyTextField;
    /**
     * email field in *Module Contact Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.email
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email: prismicT.KeyTextField;
    /**
     * Tel Label field in *Module Contact Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.tel_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tel_label: prismicT.KeyTextField;
    /**
     * Tel field in *Module Contact Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.tel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tel: prismicT.KeyTextField;
    /**
     * Contact Note field in *Module Contact Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.contact_note
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    contact_note: prismicT.RichTextField;
    /**
     * Contact Planning CTA Label field in *Module Contact Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.contact_planning_cta_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    contact_planning_cta_label: prismicT.KeyTextField;
    /**
     * Illustration Head field in *Module Contact Banner*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.illustration_head
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    illustration_head: prismicT.ImageField<never>;
    /**
     * Illustration Foot field in *Module Contact Banner*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_contact_banner.illustration_foot
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    illustration_foot: prismicT.ImageField<never>;
}
/**
 * Module Contact Banner document from Prismic
 *
 * - **API ID**: `module_contact_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleContactBannerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleContactBannerDocumentData>, "module_contact_banner", Lang>;
/** Content for Module Hero Banner documents */
interface ModuleHeroBannerDocumentData {
    /**
     * illustration field in *Module Hero Banner*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    illustration: prismicT.ImageField<never>;
    /**
     * illustration alt field in *Module Hero Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration_alt
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    illustration_alt: prismicT.KeyTextField;
    /**
     * illustration logo field in *Module Hero Banner*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    illustration_logo: prismicT.RelationField<"module_logo">;
    /**
     * logo text field in *Module Hero Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.logo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_text: prismicT.RichTextField;
    /**
     * text field in *Module Hero Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * module logo field in *Module Hero Banner*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.module_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_logo: prismicT.RelationField<"module_logo">;
}
/**
 * Module Hero Banner document from Prismic
 *
 * - **API ID**: `module_hero_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleHeroBannerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleHeroBannerDocumentData>, "module_hero_banner", Lang>;
/** Content for Module Logo documents */
interface ModuleLogoDocumentData {
    /**
     * image field in *Module Logo*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link field in *Module Logo*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * size field in *Module Logo*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.size
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    size: prismicT.NumberField;
    /**
     * no link field in *Module Logo*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: module_logo.no_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    no_link: prismicT.BooleanField;
}
/**
 * Module Logo document from Prismic
 *
 * - **API ID**: `module_logo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleLogoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleLogoDocumentData>, "module_logo", Lang>;
/** Content for Module Service documents */
interface ModuleServiceDocumentData {
    /**
     * Title field in *Module Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_service.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Module Service*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_service.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Module Service*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_service.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Image Position field in *Module Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_service.image_position
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    image_position: prismicT.KeyTextField;
}
/**
 * Module Service document from Prismic
 *
 * - **API ID**: `module_service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleServiceDocumentData>, "module_service", Lang>;
/** Content for Site Footer documents */
interface SiteFooterDocumentData {
    /**
     * Credits CTA Label field in *Site Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.credits_cta_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    credits_cta_label: prismicT.KeyTextField;
    /**
     * Credits Content field in *Site Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.credits_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    credits_content: prismicT.RichTextField;
    /**
     * Legal Mention CTA Label field in *Site Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.legal_mention_cta_label
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    legal_mention_cta_label: prismicT.KeyTextField;
    /**
     * Legal Mention Content field in *Site Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.legal_mention_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    legal_mention_content: prismicT.RichTextField;
    /**
     * Module Logo field in *Site Footer*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.module_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_logo: prismicT.RelationField<"module_logo">;
    /**
     * Copyright Content field in *Site Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.copyright_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright_content: prismicT.RichTextField;
    /**
     * Planning Content field in *Site Footer*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: site_footer.planning_content
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    planning_content: prismicT.KeyTextField;
}
/**
 * Site Footer document from Prismic
 *
 * - **API ID**: `site_footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteFooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SiteFooterDocumentData>, "site_footer", Lang>;
export type AllDocumentTypes = HomePageDocument | ModuleContactBannerDocument | ModuleHeroBannerDocument | ModuleLogoDocument | ModuleServiceDocument | SiteFooterDocument;
/**
 * Primary content in ProblematicsBlock → Primary
 *
 */
interface ProblematicsBlockSliceDefaultPrimary {
    /**
     * Text 1 field in *ProblematicsBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: problematics_block.primary.text_1
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text_1: prismicT.RichTextField;
    /**
     * Text 2 field in *ProblematicsBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: problematics_block.primary.text_2
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text_2: prismicT.RichTextField;
    /**
     * Illustration field in *ProblematicsBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: problematics_block.primary.illustration
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    illustration: prismicT.ImageField<never>;
}
/**
 * Item in ProblematicsBlock → Items
 *
 */
export interface ProblematicsBlockSliceDefaultItem {
    /**
     * Question field in *ProblematicsBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: problematics_block.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    question: prismicT.KeyTextField;
}
/**
 * Default variation for ProblematicsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProblematicsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProblematicsBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProblematicsBlockSliceDefaultPrimary>, Simplify<ProblematicsBlockSliceDefaultItem>>;
/**
 * Slice variation for *ProblematicsBlock*
 *
 */
type ProblematicsBlockSliceVariation = ProblematicsBlockSliceDefault;
/**
 * ProblematicsBlock Shared Slice
 *
 * - **API ID**: `problematics_block`
 * - **Description**: `ProblematicsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProblematicsBlockSlice = prismicT.SharedSlice<"problematics_block", ProblematicsBlockSliceVariation>;
/**
 * Primary content in ReviewsBlock → Primary
 *
 */
interface ReviewsBlockSliceDefaultPrimary {
    /**
     * Title field in *ReviewsBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: reviews_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Detail Label field in *ReviewsBlock → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: reviews_block.primary.detail_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    detail_label: prismicT.KeyTextField;
    /**
     * Link field in *ReviewsBlock → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: reviews_block.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in ReviewsBlock → Items
 *
 */
export interface ReviewsBlockSliceDefaultItem {
    /**
     * Author field in *ReviewsBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: reviews_block.items[].author
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    author: prismicT.KeyTextField;
    /**
     * Review field in *ReviewsBlock → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: reviews_block.items[].review
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    review: prismicT.RichTextField;
}
/**
 * Default variation for ReviewsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ReviewsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ReviewsBlockSliceDefaultPrimary>, Simplify<ReviewsBlockSliceDefaultItem>>;
/**
 * Slice variation for *ReviewsBlock*
 *
 */
type ReviewsBlockSliceVariation = ReviewsBlockSliceDefault;
/**
 * ReviewsBlock Shared Slice
 *
 * - **API ID**: `reviews_block`
 * - **Description**: `ReviewsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ReviewsBlockSlice = prismicT.SharedSlice<"reviews_block", ReviewsBlockSliceVariation>;
/**
 * Primary content in ServicesBlock → Primary
 *
 */
interface ServicesBlockSliceDefaultPrimary {
    /**
     * Title field in *ServicesBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: services_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Image field in *ServicesBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: services_block.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Item in ServicesBlock → Items
 *
 */
export interface ServicesBlockSliceDefaultItem {
    /**
     * module service field in *ServicesBlock → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: services_block.items[].module_service
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_service: prismicT.RelationField<"module_service">;
}
/**
 * Default variation for ServicesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ServicesBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ServicesBlockSliceDefaultPrimary>, Simplify<ServicesBlockSliceDefaultItem>>;
/**
 * Slice variation for *ServicesBlock*
 *
 */
type ServicesBlockSliceVariation = ServicesBlockSliceDefault;
/**
 * ServicesBlock Shared Slice
 *
 * - **API ID**: `services_block`
 * - **Description**: `ServicesBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ServicesBlockSlice = prismicT.SharedSlice<"services_block", ServicesBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocumentDataSlicesSlice, HomePageDocument, ModuleContactBannerDocumentData, ModuleContactBannerDocument, ModuleHeroBannerDocumentData, ModuleHeroBannerDocument, ModuleLogoDocumentData, ModuleLogoDocument, ModuleServiceDocumentData, ModuleServiceDocument, SiteFooterDocumentData, SiteFooterDocument, AllDocumentTypes, ProblematicsBlockSliceDefaultPrimary, ProblematicsBlockSliceDefaultItem, ProblematicsBlockSliceDefault, ProblematicsBlockSliceVariation, ProblematicsBlockSlice, ReviewsBlockSliceDefaultPrimary, ReviewsBlockSliceDefaultItem, ReviewsBlockSliceDefault, ReviewsBlockSliceVariation, ReviewsBlockSlice, ServicesBlockSliceDefaultPrimary, ServicesBlockSliceDefaultItem, ServicesBlockSliceDefault, ServicesBlockSliceVariation, ServicesBlockSlice };
    }
}
