// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * module hero banner field in *Home Page*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.module_hero_banner
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_hero_banner: prismicT.RelationField<"module_hero_banner">;
}
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
/** Content for Module Hero Banner documents */
interface ModuleHeroBannerDocumentData {
    /**
     * illustration field in *Module Hero Banner*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    illustration: prismicT.ImageField<never>;
    /**
     * illustration alt field in *Module Hero Banner*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration_alt
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    illustration_alt: prismicT.KeyTextField;
    /**
     * illustration logo field in *Module Hero Banner*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.illustration_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    illustration_logo: prismicT.RelationField<"module_logo">;
    /**
     * logo text field in *Module Hero Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.logo_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo_text: prismicT.RichTextField;
    /**
     * text field in *Module Hero Banner*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * module logo field in *Module Hero Banner*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: module_hero_banner.module_logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    module_logo: prismicT.RelationField<"module_logo">;
}
/**
 * Module Hero Banner document from Prismic
 *
 * - **API ID**: `module_hero_banner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleHeroBannerDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleHeroBannerDocumentData>, "module_hero_banner", Lang>;
/** Content for Module Logo documents */
interface ModuleLogoDocumentData {
    /**
     * image field in *Module Logo*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link field in *Module Logo*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * size field in *Module Logo*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: module_logo.size
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    size: prismicT.NumberField;
    /**
     * no link field in *Module Logo*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: module_logo.no_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    no_link: prismicT.BooleanField;
}
/**
 * Module Logo document from Prismic
 *
 * - **API ID**: `module_logo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ModuleLogoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ModuleLogoDocumentData>, "module_logo", Lang>;
export type AllDocumentTypes = HomePageDocument | ModuleHeroBannerDocument | ModuleLogoDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocument, ModuleHeroBannerDocumentData, ModuleHeroBannerDocument, ModuleLogoDocumentData, ModuleLogoDocument, AllDocumentTypes };
    }
}
