// Code generated by Slice Machine. DO NOT EDIT.

import AboutContact from './AboutContact';
import AboutTitleBlock from './AboutTitleBlock';
import Formation from './Formation';
import HeaderLinks from './HeaderLinks';
import HorizontalSliderBlocks from './HorizontalSliderBlocks';
import ProblematicsBlock from './ProblematicsBlock';
import RectTextBlock from './RectTextBlock';
import ReviewsBlock from './ReviewsBlock';
import RoundTextBlock from './RoundTextBlock';
import ServiceInfoBlock from './ServiceInfoBlock';
import ServicesBlock from './ServicesBlock';
import SocialMediaBlock from './SocialMediaBlock';

export {
	AboutContact,
	AboutTitleBlock,
	Formation,
	HeaderLinks,
	HorizontalSliderBlocks,
	ProblematicsBlock,
	RectTextBlock,
	ReviewsBlock,
	RoundTextBlock,
	ServiceInfoBlock,
	ServicesBlock,
	SocialMediaBlock,
};

export const components = {
	about_contact: AboutContact,
	about_title_block: AboutTitleBlock,
	formation: Formation,
	header_link: HeaderLinks,
	horizontal_slider_blocks: HorizontalSliderBlocks,
	problematics_block: ProblematicsBlock,
	rect_text_block: RectTextBlock,
	reviews_block: ReviewsBlock,
	round_text_block: RoundTextBlock,
	service_info_block: ServiceInfoBlock,
	services_block: ServicesBlock,
	social_media_block: SocialMediaBlock,
};
