// Code generated by Slice Machine. DO NOT EDIT.

import ProblematicsBlock from './ProblematicsBlock'
import ReviewsBlock from './ReviewsBlock'
import ServicesBlock from './ServicesBlock'

export { ProblematicsBlock, ReviewsBlock, ServicesBlock }

export const components = {
  problematics_block: ProblematicsBlock,
  reviews_block: ReviewsBlock,
  services_block: ServicesBlock,
}
