// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  about_contact: () =>
    import(
      /* webpackChunkName: "prismic__slices__about_contact" */ './AboutContact/index.vue'
    ),
  about_title_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__about_title_block" */ './AboutTitleBlock/index.vue'
    ),
  announcement_bar: () =>
    import(
      /* webpackChunkName: "prismic__slices__announcement_bar" */ './AnnouncementBar/index.vue'
    ),
  formation: () =>
    import(
      /* webpackChunkName: "prismic__slices__formation" */ './Formation/index.vue'
    ),
  header_link: () =>
    import(
      /* webpackChunkName: "prismic__slices__header_link" */ './HeaderLinks/index.vue'
    ),
  horizontal_slider_blocks: () =>
    import(
      /* webpackChunkName: "prismic__slices__horizontal_slider_blocks" */ './HorizontalSliderBlocks/index.vue'
    ),
  problematics_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__problematics_block" */ './ProblematicsBlock/index.vue'
    ),
  rect_text_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__rect_text_block" */ './RectTextBlock/index.vue'
    ),
  reviews_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__reviews_block" */ './ReviewsBlock/index.vue'
    ),
  round_text_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__round_text_block" */ './RoundTextBlock/index.vue'
    ),
  service_info_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__service_info_block" */ './ServiceInfoBlock/index.vue'
    ),
  services_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__services_block" */ './ServicesBlock/index.vue'
    ),
  social_media_block: () =>
    import(
      /* webpackChunkName: "prismic__slices__social_media_block" */ './SocialMediaBlock/index.vue'
    ),
}
